# Generated by Django 3.0.1 on 2020-01-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('altura', models.CharField(max_length=5)),
                ('num_gols', models.IntegerField()),
                ('num_assistencias', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Jogadores',
            },
        ),
    ]
